service: example

provider:
  name: aws
  # Default the runtime - can be overridden
  runtime: nodejs10.x

functions:
  basicLambda:
  
    # Handler function that will be called
    handler: lambda.handler

    # Name of the lambda when deployed to AWS
    name: ${self:provider.stage}-basicLambda

    # Setup environment variables
    environment:
      TEST: World

    # Setup lambda trigger events, in this case an API Gateway http GET request
    events:
      - http:
          path: hello
          method: get

  anotherLambda:
    handler: lambda.handler
    name: ${self:provider.stage}-anotherLambda
    environment:
      TEST: There
    events:
      - http:
          path: hi
          method: get