service: example

provider:
  name: aws
  runtime: nodejs10.x

functions:
  basicLambda:
    handler: lambda.handler
    name: ${self:provider.stage}-basicLambda
    environment:
      TEST: World
    events:
      - http:
          path: hello
          method: get

  anotherLambda:
    handler: lambda.handler
    name: ${self:provider.stage}-anotherLambda
    environment:
      TEST: There
    events:
      - http:
          path: hi
          method: get